const express = require('express');
const nodemailer = require('nodemailer');
const cors = require('cors');
require('dotenv').config();

const app = express();
app.use(cors());
app.use(express.json({ limit: '50mb' })); // Allow large PDF base64

const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST,
  port: process.env.SMTP_PORT,
  secure: true, // true for 465, false for other ports
  auth: {
    user: process.env.ZOHO_EMAIL,
    pass: process.env.ZOHO_PASSWORD,
  },
});

app.post('/api/send-report', async (req, res) => {
  const { to, cc, projectName, pdfBase64 } = req.body;

  const mailOptions = {
    from: `"Meaven Intelligence" <${process.env.ZOHO_EMAIL}>`,
    to: to,
    cc: cc,
    subject: `[AUDIT COMPLETE] Site Readiness Report: ${projectName}`,
    text: `Hello,\n\nPlease find the attached Site-Readiness Audit Report for ${projectName} generated by Meaven Intelligence.\n\nStatus: Ready for Execution.\n\nRegards,\nMeaven Intelligence DSS`,
    attachments: [
      {
        filename: `${projectName}_Audit_Report.pdf`,
        content: pdfBase64.split('base64,')[1],
        encoding: 'base64',
      },
    ],
  };

  try {
    await transporter.sendMail(mailOptions);
    res.status(200).json({ success: true, message: 'Email sent successfully' });
  } catch (error) {
    console.error('SMTP Error:', error);
    res.status(500).json({ success: false, message: 'Failed to send email', error: error.message });
  }
});

const PORT = 3001;
app.listen(PORT, () => {
  console.log(`Email server running on http://localhost:${PORT}`);
});
